# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Hello from AlbanianXrm
        run: echo Hello, world from AlbanianXrm!
     
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
      
      - name: Restore Packages
        run: | 
          nuget.exe restore "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions.sln"
          nuget.exe install ILMerge -Version 3.0.41 -OutputDirectory "$Env:GITHUB_WORKSPACE\Packages"
          nuget.exe install ILMerge.MSBuild.Task -Version 1.0.7 -OutputDirectory "$Env:GITHUB_WORKSPACE\Packages"
          nuget.exe install Microsoft.CrmSdk.CoreAssemblies -Version 9.0.2.26 -OutputDirectory "$Env:GITHUB_WORKSPACE\Packages"
          nuget.exe install Microsoft.CrmSdk.CoreAssemblies -Version 9.0.2.5 -OutputDirectory "$Env:GITHUB_WORKSPACE\Packages"
          Copy-Item "$Env:GITHUB_WORKSPACE\Packages\ILMerge.3.0.41\ILMerge.3.0.41.nupkg" -Destination "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions\Packages\ILMerge.3.0.41.nupkg"
          Copy-Item "$Env:GITHUB_WORKSPACE\Packages\ILMerge.MSBuild.Task.1.0.7\ILMerge.MSBuild.Task.1.0.7.nupkg" -Destination "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions\Packages\ILMerge.MSBuild.Task.1.0.7.nupkg"
          Copy-Item "$Env:GITHUB_WORKSPACE\Packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.26\Microsoft.CrmSdk.CoreAssemblies.9.0.2.26.nupkg" -Destination "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions\Packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.26.nupkg"
          Copy-Item "$Env:GITHUB_WORKSPACE\Packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.5\Microsoft.CrmSdk.CoreAssemblies.9.0.2.5.nupkg" -Destination "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions\Packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.5.nupkg"
      
      - name: Build Solution
        run: MsBuild.exe "$Env:GITHUB_WORKSPACE\AlbanianXrm Extensions.sln"
      
      - uses: actions/upload-artifact@master
        with:
          name: AlbanianXrm.Extensions
          path: AlbanianXrm Extensions\bin\Debug\AlbanianXrm Extensions.vsix
        
